apiVersion: v1
kind: ConfigMap
metadata:
  name: jasminegraph-config
  labels:
    application: jasminegraph
data:
  pushgateway_address: "${pushgateway_address}"
  prometheus_address: "${prometheus_address}"
  max_worker_count: "${max_worker_count}"
  auto_scaling_enabled: "true"
  scale_on_adgr: "false"
