apiVersion: v1
kind: Service
metadata:
  name: jasminegraph-master-service
  labels:
    application: jasminegraph
    service: jasminegraph-master
spec:
  ports:
    - port: 7777
      name: 'frontend-port'
      nodePort: 30001
    - port: 7778
      name: 'backend-port'
      nodePort: 30002
    - port: 7776
      name: 'frontend-ui-port'
      nodePort: 30003
  selector:
    type: master
    service: jasminegraph
  type: NodePort
